### ISSUE TITLE
Error when running trivial cycle app

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs/cyclejs#531]
**Code to reproduce the issue:**
```ts
import xs, { Stream } from 'xstream';
import { VNode, div } from '@cycle/dom';

import { Sources, Sinks } from './interfaces';

export function App(sources : Sources) : Sinks
{
    const vdom$ : Stream<VNode> = xs.of(
        div('', {}, ['My Awesome Cycle.js app'])
    );

    return {
        DOM: vdom$
    };
}
```
The full code can be found [here](https://github.com/cyclejs-community/create-cycle-app-flavors/pull/13) 
Usage: `git clone https://github.com/cyclejs-community/create-cycle-app-flavors.git && cd create-cycle-app-flavors && git checkout one-fits-all-unified && cd .. && create-cycle-app test --flavor $(pwd)/create-cycle-app-flavors/packages/cycle-scripts-one-fits-all && cd test && npm start`

**Expected behavior:**
No errors

**Actual behavior:**
```
TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
 at Object.removeChild (htmldomapi.js:18)
 at removeVnodes (snabbdom.js:153) 
 at updateChildren (snabbdom.js:233) 
 at patchVnode (snabbdom.js:256) 
 at patch (snabbdom.js:28)
```

**Versions of packages used:**
```
'@cycle/dom@15.0.0',
'@cycle/http@12.0.0',
'@cycle/run@1.0.0',
'xstream@10.2.0'
```

**Comment by staltz** [comment]
I didn't get that error, but instead I got a blank page (so nothing was rendered through snabbdom).

It's certainly an issue in snabbdom:

`div('', {}, ['My Awesome Cycle.js app'])` => blank
`div({}, ['My Awesome Cycle.js app'])` => worked
`div('.foo', {}, ['My Awesome Cycle.js app'])` => worked
`div('#foo', {}, ['My Awesome Cycle.js app'])` => worked

**Comment by staltz** [comment]
I'll close this issue because I made an issue for snabbdom

**Comment by staltz** [comment]
Reopening because this was related to Cycle's hyperscript-helpers, e.g. `div()`.

**Comment by jvanbruegge** [comment]
yeah, but it happens with snabbdom h too (or at least an older version of it) as this is happening with snabbdom-jsx too

**Comment by geovanisouza92** [comment]
@staltz maybe the helpers could be removed, as per #508 ?

**Comment by staltz** [comment]
> yeah, but it happens with snabbdom h too (or at least an older version of it) as this is happening with snabbdom-jsx too

Then that's a separate issue with a different reproduction case. The source of the problem could be in snabbdom-jsx, snabbdom, Cycle DOM, etc.

**Comment by staltz** [comment]
This issue is now fixed in Cycle DOM v15.1.0

**Comment by Steelfish** [comment]
Although the div is rendered on my side, I am still seeing the type error with Cycle DOM v15.1.0 on Chrome.
